### PR TITLE
Delete orphan `Data`, `Ord` instances for `MetadataMap`.

### PR DESCRIPTION
**Pull request by jsoo1**
Which are both upstream.

### CODE REVIEW

**Review by riz0id — APPROVED** [review]
thank you!

**Comment by jsoo1** [comment]
> thank you!

You're welcome!

**Comment by jsoo1** [comment]
@riz0id Are these failures catching this bug? https://github.com/awakesecurity/grpc-mqtt/blob/4dbf3df65be462e31a125a4993fda51ce911b728/test/Test/Service.hs#L165

**Comment by riz0id** [comment]
> @riz0id Are these failures catching this bug?
> 
> https://github.com/awakesecurity/grpc-mqtt/blob/4dbf3df65be462e31a125a4993fda51ce911b728/test/Test/Service.hs#L165
> 
> And are they legit failures or existing failures?

Rerunning CI produced a different error, let me see if tasty is running test groups concurrently since `-N4` is set in the RTS options. Multiple tests running with different remote clients on the same broker could cause the both issues here.

**Comment by riz0id** [comment]
The client timeout exception is a symptom of using `replicateConcurrently` inside `withMQTTGRPCClient`. I don't believe `withMQTTGRPCClient` was intended to be used this way. If clients *should* support managing multiple threads each publishing to a remote client, then clearly some work needs to be done to enable that and more tests need to be added to figure out why that doesn't work currently.

After removing `replicateConcurrently` in the "LongBytes" test, the "Test.Service.ClientStream.Unbatched" test inconsistently throws the following error [which is raised here](https://github.com/awakesecurity/grpc-mqtt/blob/4dbf3df65be462e31a125a4993fda51ce911b728/src/Network/GRPC/MQTT/Option.hs#L220):

```
ClientErrorNoParse (EmbeddedError "decoding field #2 \"options\" of record \"Request\" raised" (Just (EmbeddedError "decoding Network.GRPC.MQTT.Option.ProtoOptions raised" (Just (WireTypeError "expected 3 varints, got 0")))))
```

I can't reproduce this failure locally. @rkaippully mentioned that there was some strange `Test.Service` test failures in CI that he encountered. I'll be doing more testing tomorrow in order to reproduce this CI failure locally.

**Comment by rkaippully** [comment]
I had to adjust a few timeout values to get it working: https://github.com/awakesecurity/grpc-mqtt/pull/44/files#diff-e6b6d13ab02f568493ea0bb896278386f83ebb64b8844149aea75eb490e68144. Tests passed after that.

**Comment by Friede80** [comment]
> The client timeout exception is a symptom of using `replicateConcurrently` inside `withMQTTGRPCClient`. I don't believe `withMQTTGRPCClient` was intended to be used this way.

@riz0id This is correct. A given `MQTTGRPCClient` is not thread-safe. Maybe we should add a comment somewhere to make that clear.

**Comment by jsoo1** [comment]
I see @Friede80. Should the parallelism in the test be removed, then?

**Comment by riz0id** [comment]
> I see @Friede80. Should the parallelism in the test be removed, then?

I've remove the concurrent senders in the tests for this PR already. I will create a separate PR branching off fixing the proto serialization issue shortly.

**Comment by riz0id** [comment]
@jsoo1 Okay, the issue was in slight differences between in how `ProtoOptions` are serialized vs. how they are parsed ([`packedVarints`](https://github.com/awakesecurity/grpc-mqtt/blob/4dbf3df65be462e31a125a4993fda51ce911b728/src/Network/GRPC/MQTT/Option.hs#L217) vs [`packedVarintsV`](https://github.com/awakesecurity/grpc-mqtt/blob/4dbf3df65be462e31a125a4993fda51ce911b728/src/Network/GRPC/MQTT/Option.hs#L196)). I opened PR #49 which fixes this. I can't seem to merge that PR into this one for whatever reason, do you want to merge into that PR and I can merge it to main after it gets approval?

**Comment by jsoo1** [comment]
@riz0id I think this one can be closed in favor of #49

**Comment by riz0id** [comment]
Okay. Thanks again and sorry this got in the way of your changes.

**Comment by jsoo1** [comment]
No worries! Thank you for the quick response!

**Pull request closed without merging**
